example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('wishlist/', include('wishlist.urls')),
]

wishlist/urls.py
from django.urls import path
from wishlist.views import *

app_name = 'wishlist'

urlpatterns = [
    path('', show_wishlist, name='show_wishlist'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('json/<int:id>', show_json_by_id, name='show_json_by_id'),
    path('xml/<int:id>', show_xml_by_id, name='show_xml_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('ajax/', wishlist_ajax, name='wishlist_ajax'),
    path('ajax/submit/', add_wishlist, name='add_wishlist'),
]

example_app/models.py
from django.db import models

# Create your models here.

wishlist/models.py
from django.db import models

# Create your models here.

class BarangWishlist(models.Model):
    nama_barang = models.CharField(max_length=50)
    harga_barang = models.IntegerField()
    deskripsi = models.TextField()

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

wishlist/views.py
from django.shortcuts import render
from wishlist.models import BarangWishlist
from django.http import HttpResponse
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt

# Create your views here.

@login_required(login_url='/wishlist/login/')
def show_wishlist(request):
    data_barang_wishlist = BarangWishlist.objects.all()
    context = {
    'list_barang': data_barang_wishlist,
    'nama': 'Caroline',
    'last_login': request.COOKIES['last_login'],
   }
    return render(request, "wishlist.html", context)

def show_xml(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_json_by_id(request, id):
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('wishlist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("wishlist:show_wishlist")) # membuat response
            response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('wishlist:login'))
    response.delete_cookie('last_login')
    return response

@login_required(login_url='/wishlist/login/')
def wishlist_ajax(req):
    context = {
        'nama': 'Caroline',
        'last_login': req.COOKIES['last_login'],
    }
    return render(req, "wishlist_ajax.html", context)

@login_required(login_url='/wishlist/login/')
@csrf_exempt
def add_wishlist(req):
    if req.method == "POST":
        nama = req.POST.get("nama")
        harga = req.POST.get("harga")
        deskripsi = req.POST.get("deskripsi")
        BarangWishlist.objects.create(nama_barang=nama, harga_barang=harga, deskripsi=deskripsi)
        return HttpResponse()
    else:
        return redirect("wishlist:show_wishlist")

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
</body>

</html>

wishlist/templates/login.html
<!doctype html>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Login</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    </head>


    <body>
        <div class = "login">
            <h1>Login</h1>
            <form method="POST" action="">
                {% csrf_token %}
                <table>
                    <tr>
                        <td>Username: </td>
                        <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
                    </tr>
                            
                    <tr>
                        <td>Password: </td>
                        <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
                    </tr>
        
                    <tr>
                        <td></td>
                        <td><input type="submit" value="Login" class="btn border rounded bg-info"></td>
                    </tr>
                </table>
            </form>
        
            {% if messages %}
                <ul>
                    {% for message in messages %}
                        <li>{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}     
                
            Belum mempunyai akun? <a href="{% url 'wishlist:register' %}">Buat Akun</a>
        
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    </body>
</html>

wishlist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  

<div class = "login">
    
    <h1>Formulir Registrasi</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Daftar"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

wishlist/templates/wishlist.html
<!doctype html>
<html lang="en">
    
    <nav class="navbar navbar-expand-lg bg-light" >
        <div class="container-fluid"style="background-color: #c27ba0;">
          <b style="font-size: large;"class="navbar-brand" href="#">Caroline Esther</b>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown" >
            <ul class="navbar-nav">
              <li class="nav-item"style="background-color: #c27ba0;">
                <button ><a href="{% url 'wishlist:logout' %}">Logout</a></button>
              </li>
            </ul>
          </div>
        </div>
      </nav>


      <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=">
        <h3 style="color: black; text-align: center;font-family: Georgia, 'Times New Roman', Times, serif;padding: 10px;">Wishlist</h3>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
        </head>

<body>
    <table style="color: black ;margin-left:1%;" class="table bg-white"v>
        <tr class="bg-dark text-light">
        <th>Nama Barang</th>
        <th>Harga Barang</th>
        <th>Deskripsi</th>
        </tr>
        {% comment %} Tambahkan data di bawah baris ini {% endcomment %}
        {% for barang in list_barang %}
        <tr>
            <th>{{barang.nama_barang}}</th>
            <th>{{barang.harga_barang}}</th>
            <th>{{barang.deskripsi}}</th>
        </tr>
        {% endfor %}
    </table>

<h6 style="margin-left:1%;"; padding: 10px;>Sesi terakhir login: {{ last_login }}</h5>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
  </body>


</html>

wishlist/templates/wishlist_ajax.html
<!DOCTYPE html>

<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js%22%3E"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
        <title>Wishlist</title>
    </head>

    <body>
        <div class="p-4">
            <h5 class="mt-4">Tambah Barang</h5>
            <form method="POST" action="">
                {% csrf_token %}
                <table>
                <tr>
                    <td>Nama Barang: </td>
                    <td><input type="text" name="nama_barang" placeholder="Nama Barang" class="form-control" id="input_nama"></td>
                </tr>
                <tr>
                    <td>Harga Barang: </td>
                    <td><input type="text" name="harga_barang" placeholder="Harga Barang" class="form-control" id="input_harga"></td>
                </tr>
                <tr>
                    <td>Deskripsi: </td>
                    <td><input type="text" name="deskripsi" placeholder="Deskripsi" class="form-control" id="input_deskripsi"></td>
                </tr>
                </table>
            </form>
            <button id="add_wishlist" class="btn border rounded bg-info mb-5" >Tambah</button>
            <table class="table table-bordered">
                <tr>
                    <th>Nama Barang</th>
                    <th>Harga Barang</th>
                    <th>Deskripsi</th>
                </tr>
            </table>
            <h6>Sesi terakhir login: {{ last_login }}</h6>

        </div>

        <script>
            function updateTable(){
            // clear the table
            var itemCount = $(".table > tbody").children().length;
            for(var i = itemCount; i >= 2; i--){
                $(".table > tbody > tr:nth-child(" + i + ")").remove();
            }

            // pengambilan seluruh data wishlist
            $.get("http://localhost:8000/wishlist/json/", function(data) {
            // fill the table
                for(var i = 0; i < data.length; i++){
                    var tr = document.createElement("tr");
                    var tdNama = document.createElement("td");
                    tdNama.append(data[i].fields.nama_barang);
                    var tdHarga = document.createElement("td");
                    tdHarga.append(data[i].fields.harga_barang);
                    var tdDeskripsi = document.createElement("td");
                    tdDeskripsi.append(data[i].fields.deskripsi);
                    
                    tr.append(tdNama);
                    tr.append(tdHarga);
                    tr.append(tdDeskripsi);
                    
                    $(".table").append(tr);
                }
                });
            }
        
            $(document).ready(function(){
                updateTable();
            
            $("#add_wishlist").click(function(){
                var nama = $("#input_nama").val();
                var harga = $("#input_harga").val();
                var deskripsi = $("#input_deskripsi").val();

            
                $.post("http://localhost:8000/wishlist/ajax/submit/",
                {
                    nama,
                    harga,
                    deskripsi,
                },
                function(data, status){
                    console.log("add wishlist success");
                    updateTable();
                    $("#input_nama").val("");
                    $("#input_harga").val("");
                    $("#input_deskripsi").val("");
                    });
                });
            });
        </script>
    </body>

<style>
    @import url('https://fonts.googleapis.com/css2?family=Noto+Sans:wght@700&family=Poppins:wght@400;500;600&display=swap');
    *{
        box-sizing: border-box;
        font-family: "Poppins", sans-serif;
    }
    body{
        font-family: montserrat;
        min-height: 100vh;
    }
</style>